export const FETCH_TODO_LIST_REQUEST = 'FETCH_TODO_LIST_REQUEST'
export const FETCH_TODO_LIST_SUCCESS = 'FETCH_TODO_LIST_SUCCESS'
export const FETCH_TODO_LIST_FAILURE = 'FETCH_TODO_LIST_FAILURE'

export const ADD_TODO_LIST_REQUEST = 'ADD_TODO_LIST_REQUEST'
export const ADD_TODO_LIST_SUCCESS = 'ADD_TODO_LIST_SUCCESS'
export const ADD_TODO_LIST_FAILURE = 'ADD_TODO_LIST_FAILURE'

export const DELETE_TODO_SUCCESS = 'DELETE_TODO_SUCCESS'
export const DELETE_TODO_FAILURE = 'DELETE_TODO_FAILURE'
export const DELETE_TODO_REQUEST = 'DELETE_TODO_REQUEST'
